README.md, packages/hono-takibi/README.md
=> Hono Takibi🔥 change icon url

packages/hono-takibi/package.json
=> Hono Takabi🔥 Change Git Url

packages/hono-takibi/src/core/text/escape-quote.test.ts, packages/hono-takibi/src/core/text/escape-quote.ts, packages/hono-takibi/src/core/text/escape.test.ts, packages/hono-takibi/src/core/text/escape.ts, packages/hono-takibi/src/generators/hono/generate-zod-openapi-hono.test.ts, packages/hono-takibi/src/generators/hono/generate-zod-openapi-hono.ts, packages/hono-takibi/src/generators/openapi/paths/generate-route.ts, packages/hono-takibi/src/generators/response/schemas/generate-response-schema.ts, packages/hono-takibi/src/index.ts, packages/hono-takibi/src/types/index.ts
=> Hono Takibi🔥 Refactor

biome.json, packages/hono-takibi/src/generators/zod/generate-zod-integer-schema.ts, packages/hono-takibi/src/generators/zod/generate-zod-number-schema.ts, packages/hono-takibi/src/generators/zod/generate-zod-string-schema.ts, packages/hono-takibi/src/generators/zod/generate-zod-to-openapi.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-to-openapi.ts
=> generateZodToOpenAPI func apply

docs/.vitepress/config.mts, docs/docs/zod/arrays/index.md, docs/docs/zod/schema-methods/index.md, packages/hono-takibi/src/generators/zod/generate-zod-default.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-default.ts, packages/hono-takibi/src/generators/zod/generate-zod-integer-schema.ts, packages/hono-takibi/src/generators/zod/generate-zod-max.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-max.ts, packages/hono-takibi/src/generators/zod/generate-zod-min.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-min.ts, packages/hono-takibi/src/generators/zod/generate-zod-number-schema.ts, packages/hono-takibi/src/generators/zod/generate-zod-regex.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-regex.ts, packages/hono-takibi/src/generators/zod/generate-zod-string-schema.ts, packages/hono-takibi/src/generators/zod/generate-zod-to-openapi.test.ts
=> Hono Takibi🔥 Apply Pure Function

packages/hono-takibi/hono-takibi.json, packages/hono-takibi/routes/schema-not-exported-hono-rest-example.ts, packages/hono-takibi/src/config/index.ts, packages/hono-takibi/src/generators/hono/generate-zod-openapi-hono.ts, packages/hono-takibi/src/generators/openapi/components/generate-components-code.test.ts, packages/hono-takibi/src/generators/openapi/components/generate-components-code.ts, packages/hono-takibi/src/index.ts
```ts
import { createRoute, z } from '@hono/zod-openapi'
const errorSchema = z.object({ message: z.string() }).openapi('Error')
const postSchema = z
.object({
id: z.string().uuid(),
post: z.string().min(1).max(140),
createdAt: z.string().datetime(),
updatedAt: z.string().datetime(),
})
.openapi('Post')
export const getRoute = createRoute({
tags: ['Hono'],
method: 'get',
path: '/',
summary: 'Welcome message',
description: 'Retrieve a simple welcome message from the Hono API.',
responses: {
200: {
description: 'Successful response with a welcome message.',
content: {
'application/json': {
schema: z.object({ message: z.string().openapi({ example: 'Hono🔥' }) }),
},
},
},
},
})
export const postPostsRoute = createRoute({
tags: ['Post'],
method: 'post',
path: '/posts',
summary: 'Create a new …
```
=> Hono Takibi🔥 add Schema option

packages/hono-takibi/index.ts, packages/hono-takibi/openapi/openapi-complex-array.yaml, packages/hono-takibi/route/openapi-complex-array.ts, packages/hono-takibi/src/generators/zod/generate-zod-gt.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-length.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-lt.test.ts, packages/hono-takibi/src/generators/zod/generate-zod-object-schema.test.ts, packages/hono-takibi/src/generators/zod/schema/generate-zod-schema.test.ts, packages/hono-takibi/src/generators/zod/schema/generate-zod-schema.ts
=> Hono Takibi🔥 Add Test and array.length support

README.md, packages/hono-takibi/README.md, packages/hono-takibi/src/index.ts
=> Hono Takabi🔥 fix README.md warn Message ...Other

docs/.vitepress/config.mts, docs/.vitepress/theme/custom.css, docs/.vitepress/theme/index.ts, docs/docs/index.md, docs/docs/purpose/index.md, docs/index.md, docs/package.json, package.json, pnpm-workspace.yaml
=> Hono-Takibi🔥 VitePress

packages/hono-takibi/src/core/schema/references/extract-refs.test.ts, packages/hono-takibi/src/core/schema/references/extract-refs.ts, packages/hono-takibi/src/core/schema/references/get-ref-schema-name.test.ts, packages/hono-takibi/src/core/schema/references/get-ref-schema-name.ts, packages/hono-takibi/src/core/schema/references/traverse-schema-dependencies.ts, packages/hono-takibi/src/core/validator/is-format-number.ts, packages/hono-takibi/src/core/validator/is-ref-object.ts, packages/hono-takibi/src/core/validator/is-schema-reference.ts, packages/hono-takibi/src/core/zod/get-zod-string-format.test.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/docs/generate-docs.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/generate-app-route-handler.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/index.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/register-component/generate-register-component.ts, packages/hono-takibi/src/generator/zod-openapi-hono/handler/generate-handler-name.ts, packages/hono-takibi/src/generator/zod-openapi-hono/handler/helper/group-handlers-by-file-name-helper.ts, packages/hono-takibi/src/generator/zod-openapi-hono/handler/import/generate-import-handlers.ts, packages/hono-takibi/src/generator/zod-openapi-hono/handler/import/get-handler-imports.ts, packages/hono-takibi/src/generator/zod/generate-zod-enum.test.ts, packages/hono-takibi/src/generator/zod/generate-zod-enum.ts, packages/hono-takibi/src/generator/zod/generate-zod-number.test.ts, packages/hono-takibi/src/generator/zod/generate-zod-object.test.ts, packages/hono-takibi/src/type/index.ts, packages/hono-takibi/src/vite-plugin/index.ts
=> Hono Takibi🔥 Add Test And TsDoc

.github/workflows/test.yml, apps/openapi_hono_drizzle/package.json, apps/openapi_hono_prisma/package.json, packages/hono-takibi/package.json
=> fix workflow other

package.json, packages/hono-takibi/package.json, packages/hono-takibi/src/generator/zod-openapi-hono/app/docs/generate-docs.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/helper/get-route-maps.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/index.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/register-component/generate-register-component.ts, packages/hono-takibi/src/index.ts, packages/hono-takibi/tsconfig.json
=> Hono Takibi🔥 Type Module

apps/openapi_hono_drizzle/package.json, apps/openapi_hono_drizzle/src/index.ts, apps/openapi_hono_drizzle/vite.config.ts, apps/openapi_hono_prisma/package.json
=> hono-takibi example version up

packages/hono-takibi/src/vite-plugin/index.ts, packages/hono-takibi/vite.config.ts
=> Hono Takibi🔥 HonoTakibiVite

packages/hono-takibi/src/generator/zod-openapi-hono/openapi/components/oneof/index.test.ts, packages/hono-takibi/src/generator/zod-openapi-hono/openapi/components/oneof/index.ts
=> Hono Takibi🔥 fix oneOf logic

packages/hono-takibi/package.json, packages/hono-takibi/routes/openapi-complex-array.ts, packages/hono-takibi/routes/openapi-number.ts, packages/hono-takibi/src/generator/zod-openapi-hono/openapi/route/params/params-object.test.ts, packages/hono-takibi/src/generator/zod/index.test.ts, packages/hono-takibi/src/generator/zod/index.ts, packages/hono-takibi/src/generator/zod/z/array.test.ts, packages/hono-takibi/src/generator/zod/z/array.ts, packages/hono-takibi/src/generator/zod/z/index.test.ts, packages/hono-takibi/src/generator/zod/z/index.ts, packages/hono-takibi/src/generator/zod/z/integer.test.ts, packages/hono-takibi/src/generator/zod/z/integer.ts, packages/hono-takibi/src/generator/zod/z/number.test.ts, packages/hono-takibi/src/generator/zod/z/number.ts, packages/hono-takibi/src/generator/zod/z/object.ts, packages/hono-takibi/src/generator/zod/z/string.ts, packages/hono-takibi/src/utils/index.test.ts, packages/hono-takibi/src/utils/index.ts
=> Hono Takibi🔥 number integer logic fix

packages/hono-takibi/src/generator/zod/helper/array-reference-schema.test.ts, packages/hono-takibi/src/generator/zod/helper/array-reference-schema.ts, packages/hono-takibi/src/utils/index.test.ts, packages/hono-takibi/src/utils/index.ts
=> array method delete

apps/zod-openapi-hono-prisma/src/routes/index.ts, apps/zod-openapi-hono-prisma/src/rpc/index.ts
=> fix Example

package.json, packages/hono-takibi/package.json, packages/hono-takibi/src/index.test.ts, packages/hono-takibi/src/openapi/index.ts, pnpm-workspace.yaml
=> OpenAPI validate Fix

fixtures/generate/rpcs/hono-rest-example.ts, packages/hono-takibi/src/cli/index.ts, packages/hono-takibi/src/config/index.ts, packages/hono-takibi/src/generator/rpc/index.test.ts, packages/hono-takibi/src/generator/rpc/index.ts, packages/hono-takibi/src/index.test.ts, packages/hono-takibi/src/utils/index.test.ts, packages/hono-takibi/src/utils/index.ts
=> Hono Takibi🔥 Fix Config

fixtures/split/hono-takibi.config.ts, fixtures/split/package.json, fixtures/split/src/schemas/index.ts, packages/hono-takibi/package.json, packages/hono-takibi/src/cli/index.ts, packages/hono-takibi/src/config/index.ts, packages/hono-takibi/src/core/schema.test.ts, packages/hono-takibi/src/core/schema.ts
=> Fix Config validation

packages/hono-takibi/src/generator/zod-openapi-hono/app/index.test.ts, packages/hono-takibi/src/generator/zod-openapi-hono/app/index.ts
=> fix template generator

packages/hono-takibi/package.json, packages/hono-takibi/src/core/takibi.ts, packages/hono-takibi/src/index.test.ts
=> fix template generate
